# action.yml
name: 'costinmKoAction'
description: 'Build and push with ko'
inputs:
  path:  # path to go command
    description: 'Path to go command'
    required: false
    default: './'
  tag:
    description: 'Tag'
    required: false
    default: 'latest'
  repo:
    description: 'Repo'
    required: yes
outputs:
  sha: # id of output
    description: 'Sha of the image'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    KO_DOCKER_REPO: ${{ repo }}
  args:
    - ${{ inputs.path }}
    - "-t"
    - ${{ inputs.tag }}

