name: Go
on: [push]

env:
  GO111MODULE: on

jobs:
  build-ko-image:
    name: Build-in-docker
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          local: true
          file: ./Dockerfile
          tags: |
            ghcr.io/costinm/ko-action/ko:v1

      - name: Test
        id: test
        uses: costinm/ko-action@latest
        with:
          tag: test
          repo: ghcr.io/costin/ko-action/kotest

      - name: Get the output time
        run: echo "The time was ${{ steps.test.outputs.sha }}"
